language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
  - { php: 5.5, env: "COMPOSER_FLAGS='--prefer-stable --prefer-lowest' PHPUNIT_COVERAGE='--coverage-text --coverage-clover=coverage.clover'"}
  allow_failures:
  - { php: hhvm }
  - { php: 7.0 }

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit ${PHPUNIT_COVERAGE}

after_script:
  - if [[ "${PHPUNIT_COVERAGE}" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "${PHPUNIT_COVERAGE}" != "" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  
